#!/usr/bin/env ruby
#^syntax detection

#FIXME: all these should be replaced with the opscode cookbooks
site 'http://community.opscode.com/api/v1'


%w(apache2 mysql apt memcached php git).each do |cb| 
  cookbook cb 
end

cookbook "xhprof", :git => "git://github.com/msonnabaum/chef-xhprof.git"
cookbook "drush", :git => "git://github.com/msonnabaum/chef-drush.git"

# cookbook "drush_make"
# cookbook "phpmyadmin" 
# cookbook "webgrind" 
# cookbook "imagemagick"
# cookbook "varnish"

